name: home_ease
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.2
  url_launcher: ^6.3.1
  url_launcher_android: ^6.3.14
  fl_chart: ^0.70.1
  intl: ^0.20.1
  syncfusion_flutter_charts: ^28.1.38
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  lottie: ^3.3.1
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.5
  month_picker_dialog: ^6.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/HomEase.png
    - assets/task_management.png
    - assets/service_contact.png
    - assets/tips_and_tricks.png
    - assets/analysis.png
    - assets/home_main1.png
    - assets/home_main2.png
    - assets/success.json
    - assets/analysis.json
    - assets/servicecontact.json
    - assets/tasks.json
    - assets/tipsandtricks.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/HomEase.png"
