// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZJ5OCRuGm5tWW3iGa1u9_YECeuUw5Uk0',
    appId: '1:754855128071:web:892f1220096ef8d9e98ea2',
    messagingSenderId: '754855128071',
    projectId: 'homease-274b5',
    authDomain: 'homease-274b5.firebaseapp.com',
    storageBucket: 'homease-274b5.firebasestorage.app',
    measurementId: 'G-DL16FFJ5WR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKflUw8wxrPR1UmcTDd2ob_IGPxmYXgKo',
    appId: '1:754855128071:android:1ac2cb4e767b8a18e98ea2',
    messagingSenderId: '754855128071',
    projectId: 'homease-274b5',
    storageBucket: 'homease-274b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_nS-3Rn-TZHm-7ffB4SbHHiBoxd7jSpk',
    appId: '1:754855128071:ios:7f8e623f82b10932e98ea2',
    messagingSenderId: '754855128071',
    projectId: 'homease-274b5',
    storageBucket: 'homease-274b5.firebasestorage.app',
    iosBundleId: 'com.example.homeEase',
  );
}
